version: '3.5'

services:
  s3:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    volumes:
      - minio_vol:/data
    ports:
      - 8000:8000
    environment:
      - MINIO_ROOT_USER=adminuser
      - MINIO_ROOT_PASSWORD=adminuser
    command: server --console-address ":8000" /data/test_bucket
    restart: on-failure

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 adminuser adminuser;
      /usr/bin/mc mb myminio/test_bucket;
      /usr/bin/mc policy set public myminio/test_bucket;
      exit 0;
      "

  mlflow:
    build:
      context: mlflow
      dockerfile: Dockerfile
    volumes:
      - mlflow_vol:/app
    environment:
      - TEST=test
    ports:
      - 3000:5000
  
volumes:
  minio_vol:
  mlflow_vol:


  